# -*- coding: utf-8 -*-
"""CodeTA_StressLevelDataset_Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShjaiwILIJS6TLh-nUYxuqJQD7hAaNOP

CodeTA_StressLevelDataset - Dengan Integrasi W&B (Weights & Biases)
=======================================================================
Penelitian: Explainable AI untuk Prediksi Tingkat Stres Mahasiswa
            Perbandingan XGBoost, Random Forest, LightGBM
Penulis   : Kevin Philips Tanamas (220711789)
Framework : CRISP-DM


W&B digunakan sebagai pembuktian terbalik:
  - Setiap run otomatis merekam semua hyperparameter model
  - Semua metrik evaluasi (Accuracy, Macro F1, ROC-AUC, per-class) dicatat
  - Cross-validation tiap fold dilog satu per satu
  - Confusion matrix dan feature importance divisualisasikan otomatis
  - Perbandingan ketiga model tersedia di W&B Dashboard
'''

## WanDB - Pembuktian Terbalik Setiap Parameter
"""

pip install wandb

import wandb
wandb.login(key="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")

import os
import wandb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ─── Konfigurasi Proyek W&B ──────────────────────────────
WANDB_PROJECT = "stress-level-prediction"   # nama project di wandb.ai
WANDB_ENTITY  = None  # username/team W&B kamu, atau None (pakai default)

"""## Drive Configuration"""

from google.colab import drive
drive.mount('/content/drive')

"""## Business & Data Understanding"""

# ==========================================================
# Explainable AI: Prediksi Stress Mahasiswa Menggunakan XGBoost, RF, dan LightGBM
# Framework: CRISP-DM
# ==========================================================

# ==========================================================
# 1. BUSINESS UNDERSTANDING
# ==========================================================
# Tujuan:
# Membangun model prediksi tingkat stres mahasiswa
# menggunakan Random Forest, XGBoost, dan LightGBM
# serta mengintegrasikan Explainable AI (SHAP)

# ==========================================================
# 2. DATA UNDERSTANDING
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

run_data = wandb.init(
    project=WANDB_PROJECT,
    entity=WANDB_ENTITY,
    name="01_data_understanding",
    tags=["crisp-dm", "eda", "data-understanding"],
    config={
        "dataset": "StressLevelDataset.csv",
        "n_classes": 3,
        "target": "stress_level",
        "class_labels": {0: "Rendah", 1: "Sedang", 2: "Tinggi"},
    }
)

df = pd.read_csv("/content/drive/MyDrive/Dataset/StressLevelDataset.csv")

run_data.log({
    "data/n_samples": len(df),
    "data/n_features_raw": df.shape[1] - 1,  # exclude target
    "data/missing_values_total": df.isnull().sum().sum(),
    "data/duplicates": df.duplicated().sum(),
    "data/class_0_count": (df["stress_level"] == 0).sum(),
    "data/class_1_count": (df["stress_level"] == 1).sum(),
    "data/class_2_count": (df["stress_level"] == 2).sum(),
})

# [WANDB] Log distribusi kelas sebagai tabel
class_dist = df["stress_level"].value_counts().reset_index()
class_dist.columns = ["stress_level", "count"]
class_dist["label"] = class_dist["stress_level"].map({0: "Rendah", 1: "Sedang", 2: "Tinggi"})
run_data.log({"data/class_distribution": wandb.Table(dataframe=class_dist)})

# Visualisasi Distribusi Target
fig, ax = plt.subplots(figsize=(6, 4))
sns.countplot(x="stress_level", data=df, ax=ax)
ax.set_title("Distribusi Tingkat Stres Mahasiswa")
ax.set_xlabel("Stress Level (0=Rendah, 1=Sedang, 2=Tinggi)")
ax.set_ylabel("Jumlah Mahasiswa")
run_data.log({"plots/distribusi_target": wandb.Image(fig)})
plt.show(); plt.close()

# Histogram Data Numerik
fig = plt.figure(figsize=(18, 14))
df.hist(figsize=(18, 14), bins=15)
plt.suptitle("Distribusi Seluruh Variabel", fontsize=16)
run_data.log({"plots/histogram_semua_variabel": wandb.Image(fig)})
plt.show(); plt.close()

# Korelasi
fig, ax = plt.subplots(figsize=(14, 10))
corr = df.corr()
sns.heatmap(corr, cmap="coolwarm", center=0, ax=ax)
ax.set_title("Heatmap Korelasi Antar Variabel")
run_data.log({"plots/heatmap_korelasi": wandb.Image(fig)})
plt.show(); plt.close()

# Korelasi terhadap target
corr_target = df.corr()["stress_level"].sort_values(ascending=False)
fig, ax = plt.subplots(figsize=(8, 6))
corr_target.drop("stress_level").plot(kind="bar", ax=ax)
ax.set_title("Korelasi Fitur terhadap Stress Level")
ax.set_ylabel("Nilai Korelasi")
run_data.log({"plots/korelasi_fitur_target": wandb.Image(fig)})
plt.show(); plt.close()

# [WANDB] Log nilai korelasi tiap fitur sebagai tabel
corr_table = corr_target.drop("stress_level").reset_index()
corr_table.columns = ["feature", "pearson_corr"]
run_data.log({"data/feature_correlations": wandb.Table(dataframe=corr_table)})

# Box Plot Fitur Penting
important_features = ["anxiety_level", "depression", "future_career_concerns",
                       "academic_performance", "social_support"]
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
for i, col in enumerate(important_features):
    ax = axes[i // 3][i % 3]
    sns.boxplot(x="stress_level", y=col, data=df, ax=ax)
plt.tight_layout()
run_data.log({"plots/boxplot_fitur_penting": wandb.Image(fig)})
plt.show(); plt.close()

run_data.finish()
print("[W&B] Run '01_data_understanding' selesai.")

# Distribusi Fitur Psikologis
psychological = ["anxiety_level", "depression", "self_esteem"]

df[psychological].plot(kind="box", figsize=(8,5))
plt.title("Distribusi Faktor Psikologis")
plt.show()

"""## Data Preparation"""

# ==========================================================
# 3. DATA PREPARATION
# ==========================================================

# ---------- 3.1 Handling Missing Values ----------
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].median())

# ---------- 3.2 Feature Engineering ----------
def minmax_norm(series: pd.Series) -> pd.Series:
    """Normalisasi min-max ke rentang [0, 1]."""
    return (series - series.min()) / (series.max() - series.min())

# Academic Stress Index (Correlation-Weighted Composite)
_corr_target = df.corr()["stress_level"]
_w_study  = abs(_corr_target["study_load"])
_w_career = abs(_corr_target["future_career_concerns"])
_w_acad   = abs(_corr_target["academic_performance"])
_total_w  = _w_study + _w_career + _w_acad

df["academic_stress_index"] = (
    (_w_study  / _total_w) * minmax_norm(df["study_load"])
    + (_w_career / _total_w) * minmax_norm(df["future_career_concerns"])
    + (_w_acad   / _total_w) * (1 - minmax_norm(df["academic_performance"]))
)

print(f"[INFO] Bobot Academic Stress Index:")
print(f"  study_load             : {_w_study/_total_w:.4f}")
print(f"  future_career_concerns : {_w_career/_total_w:.4f}")
print(f"  academic_performance   : {_w_acad/_total_w:.4f}  (diinvers)")

# Environment Quality Index
MAX_LIVING = df["living_conditions"].max()
MAX_SAFETY = df["safety"].max()
MAX_BASIC  = df["basic_needs"].max()
df["environment_quality_index"] = (
    df["noise_level"]
    + (MAX_LIVING - df["living_conditions"])
    + (MAX_SAFETY - df["safety"])
    + (MAX_BASIC  - df["basic_needs"])
)

# Social Stress Score
df["social_stress_score"] = (
    minmax_norm(df["peer_pressure"])
    + minmax_norm(df["bullying"])
    + (1 - minmax_norm(df["social_support"]))
)

# ---------- 3.3 Feature Selection ----------
selected_features = [
    "anxiety_level", "self_esteem", "mental_health_history", "depression",
    "headache", "blood_pressure", "sleep_quality", "breathing_problem",
    "noise_level", "living_conditions", "safety", "basic_needs",
    "academic_performance", "study_load", "teacher_student_relationship",
    "future_career_concerns", "social_support", "peer_pressure",
    "extracurricular_activities", "bullying",
    "academic_stress_index", "environment_quality_index", "social_stress_score",
]
selected_features = [f for f in selected_features if f in df.columns]
print(f"\n[INFO] Jumlah fitur yang digunakan: {len(selected_features)}")

X = df[selected_features]
y = df["stress_level"]

# ---------- 3.4 Encoding Target ----------
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# ---------- 3.5 Scaling ----------
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=selected_features)

# ---------- 3.6 Train-Test Split ----------
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, stratify=y, random_state=42
)
print(f"\n[INFO] Ukuran data latih : {X_train.shape}")
print(f"[INFO] Ukuran data uji   : {X_test.shape}")

"""## Modeling"""

# ==========================================================
# 4. MODELING
# ==========================================================

from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from lightgbm import LGBMClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import (accuracy_score, f1_score, roc_auc_score,
                              confusion_matrix, classification_report)

n_classes = len(np.unique(y))

# ─── Definisi Hyperparameter (sesuai laporan) ───────────
MODEL_CONFIGS = {
    "Random Forest": {
        "model": RandomForestClassifier(
            n_estimators=300,
            max_depth=12,
            random_state=42,
        ),
        "hyperparams": {
            "n_estimators": 300,
            "max_depth": 12,
            "random_state": 42,
            "criterion": "gini",
        },
        "wandb_tags": ["random-forest", "bagging"],
    },
    "XGBoost": {
        "model": xgb.XGBClassifier(
            objective="multi:softprob",
            num_class=n_classes,
            n_estimators=300,
            learning_rate=0.05,
            max_depth=6,
            random_state=42,
        ),
        "hyperparams": {
            "n_estimators": 300,
            "learning_rate": 0.05,
            "max_depth": 6,
            "objective": "multi:softprob",
            "num_class": n_classes,
            "random_state": 42,
        },
        "wandb_tags": ["xgboost", "gradient-boosting", "best-model"],
    },
    "LightGBM": {
        "model": LGBMClassifier(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=10,
            random_state=42,
        ),
        "hyperparams": {
            "n_estimators": 300,
            "learning_rate": 0.05,
            "max_depth": 10,
            "random_state": 42,
        },
        "wandb_tags": ["lightgbm", "gradient-boosting"],
    },
}

# ==========================================================
# 5. TRAINING + EVALUATION + W&B LOGGING (per model)
# ==========================================================

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
all_results = []

for model_name, cfg in MODEL_CONFIGS.items():
    print(f"\n{'='*60}")
    print(f"[W&B] Memulai run: {model_name}")
    print(f"{'='*60}")

    # ── Inisialisasi W&B run untuk model ini ──────────────
    run = wandb.init(
        project=WANDB_PROJECT,
        entity=WANDB_ENTITY,
        name=f"02_train_{model_name.lower().replace(' ', '_')}",
        tags=["crisp-dm", "modeling", "evaluation"] + cfg["wandb_tags"],
        config={
            "model_name": model_name,
            "n_features": len(selected_features),
            "n_classes": n_classes,
            "test_size": 0.2,
            "cv_folds": 5,
            "train_samples": len(X_train),
            "test_samples": len(X_test),
            **cfg["hyperparams"],
        },
    )

    model = cfg["model"]

    # ── Cross-Validation (5-fold, Macro F1) ──────────────
    print(f"\n[INFO] Cross-Validation 5-Fold ({model_name}):")
    cv_f1_scores = []
    for fold, (train_idx, val_idx) in enumerate(cv.split(X_train, y_train), start=1):
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_val = y_train[train_idx], y_train[val_idx]

        model_temp = cfg["model"].__class__(**cfg["hyperparams"])
        model_temp.fit(X_tr, y_tr)
        fold_f1 = f1_score(y_val, model_temp.predict(X_val), average="macro")
        cv_f1_scores.append(fold_f1)
        print(f"  Fold {fold}: F1={fold_f1:.4f}")

        # [WANDB] Log tiap fold secara individual
        run.log({
            f"cv/fold_{fold}_f1_macro": fold_f1,
            "cv/fold": fold,
        })

    cv_mean = np.mean(cv_f1_scores)
    cv_std  = np.std(cv_f1_scores)
    print(f"  → Mean: {cv_mean:.4f}, Std: {cv_std:.4f}")

    # [WANDB] Log ringkasan CV
    run.log({
        "cv/f1_macro_mean": cv_mean,
        "cv/f1_macro_std": cv_std,
        "cv/f1_macro_min": np.min(cv_f1_scores),
        "cv/f1_macro_max": np.max(cv_f1_scores),
    })

    # ── Training pada seluruh data latih ─────────────────
    model.fit(X_train, y_train)

    # ── Evaluasi pada data uji ────────────────────────────
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)

    acc = accuracy_score(y_test, y_pred)
    f1  = f1_score(y_test, y_pred, average="macro")
    roc = roc_auc_score(y_test, y_prob, multi_class="ovr")

    # Per-class metrics
    report = classification_report(y_test, y_pred, output_dict=True)
    prec_0 = report["0"]["precision"]; rec_0 = report["0"]["recall"]; f1_0 = report["0"]["f1-score"]
    prec_1 = report["1"]["precision"]; rec_1 = report["1"]["recall"]; f1_1 = report["1"]["f1-score"]
    prec_2 = report["2"]["precision"]; rec_2 = report["2"]["recall"]; f1_2 = report["2"]["f1-score"]
    weighted_f1 = report["weighted avg"]["f1-score"]

    print(f"\n{model_name}")
    print(classification_report(y_test, y_pred,
          target_names=["Rendah", "Sedang", "Tinggi"]))

    # [WANDB] Log semua metrik evaluasi
    run.log({
        # Metrik utama (sesuai Tabel 5.1 di laporan)
        "eval/accuracy":        acc,
        "eval/f1_macro":        f1,
        "eval/roc_auc_ovr":     roc,
        "eval/f1_weighted":     weighted_f1,

        # Per-class: Stres Rendah (kelas 0)
        "eval/class_0_rendah/precision": prec_0,
        "eval/class_0_rendah/recall":    rec_0,
        "eval/class_0_rendah/f1":        f1_0,

        # Per-class: Stres Sedang (kelas 1)
        "eval/class_1_sedang/precision": prec_1,
        "eval/class_1_sedang/recall":    rec_1,
        "eval/class_1_sedang/f1":        f1_1,

        # Per-class: Stres Tinggi (kelas 2)
        "eval/class_2_tinggi/precision": prec_2,
        "eval/class_2_tinggi/recall":    rec_2,
        "eval/class_2_tinggi/f1":        f1_2,

        # Support (jumlah sampel per kelas di data uji)
        "eval/class_0_support": report["0"]["support"],
        "eval/class_1_support": report["1"]["support"],
        "eval/class_2_support": report["2"]["support"],
    })

    # ── Confusion Matrix ──────────────────────────────────
    cm = confusion_matrix(y_test, y_pred)
    fig_cm, ax = plt.subplots(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt="d", ax=ax,
                xticklabels=["Rendah", "Sedang", "Tinggi"],
                yticklabels=["Rendah", "Sedang", "Tinggi"])
    ax.set_title(f"Confusion Matrix – {model_name}")
    ax.set_xlabel("Predicted"); ax.set_ylabel("Actual")
    plt.tight_layout()

    # [WANDB] Log sebagai gambar DAN sebagai W&B Confusion Matrix native
    run.log({
        f"plots/confusion_matrix": wandb.Image(fig_cm),
        "eval/confusion_matrix_wandb": wandb.plot.confusion_matrix(
            probs=None,
            y_true=y_test.tolist(),
            preds=y_pred.tolist(),
            class_names=["Rendah", "Sedang", "Tinggi"],
        ),
    })
    plt.show(); plt.close()

    # ── Feature Importance (model-based) ─────────────────
    if hasattr(model, "feature_importances_"):
        fi = pd.DataFrame({
            "feature": selected_features,
            "importance": model.feature_importances_,
        }).sort_values("importance", ascending=False)

        fig_fi, ax = plt.subplots(figsize=(9, 7))
        sns.barplot(x="importance", y="feature", data=fi.head(20), ax=ax)
        ax.set_title(f"Feature Importance – {model_name}")
        plt.tight_layout()

        # [WANDB] Log tabel + plot feature importance
        run.log({
            "plots/feature_importance": wandb.Image(fig_fi),
            "data/feature_importance_table": wandb.Table(dataframe=fi),
        })
        plt.show(); plt.close()

    # ── Koleksi hasil untuk perbandingan akhir ────────────
    all_results.append({
        "Model": model_name,
        "Accuracy": acc,
        "Macro F1": f1,
        "ROC-AUC": roc,
        "CV F1 Mean": cv_mean,
        "CV F1 Std": cv_std,
        "Weighted F1": weighted_f1,
    })

    # [WANDB] Summary (muncul di overview card W&B)
    run.summary["accuracy"]     = acc
    run.summary["f1_macro"]     = f1
    run.summary["roc_auc"]      = roc
    run.summary["cv_f1_mean"]   = cv_mean
    run.summary["cv_f1_std"]    = cv_std

    run.finish()
    print(f"[W&B] Run '{model_name}' selesai.")

"""## Evaluation"""

# ==========================================================
# PERBANDINGAN MODEL — W&B Run Terpisah
# ==========================================================

print("\n[W&B] Logging perbandingan model...")
run_compare = wandb.init(
    project=WANDB_PROJECT,
    entity=WANDB_ENTITY,
    name="03_model_comparison",
    tags=["crisp-dm", "comparison", "final"],
    config={
        "models_compared": list(MODEL_CONFIGS.keys()),
        "primary_metric": "cv_f1_macro",
        "selected_best_model": "XGBoost",
        "selection_reason": "CV F1 tertinggi dan kompatibel SHAP TreeExplainer",
    }
)

results_df = pd.DataFrame(all_results)
print("\nPerbandingan Model:")
print(results_df.to_string(index=False))

# [WANDB] Log tabel perbandingan
run_compare.log({
    "comparison/model_results_table": wandb.Table(dataframe=results_df),
})

# [WANDB] Bar chart perbandingan metrik utama
metrics_to_compare = ["Accuracy", "Macro F1", "ROC-AUC", "CV F1 Mean"]
fig_comp, axes = plt.subplots(1, len(metrics_to_compare), figsize=(18, 5))
for ax, metric in zip(axes, metrics_to_compare):
    bars = ax.bar(results_df["Model"], results_df[metric],
                  color=["#4C9FE8", "#FF6B6B", "#4CAF50"])
    ax.set_title(metric, fontsize=11, fontweight="bold")
    ax.set_ylim(0.8, 1.0)
    ax.set_ylabel("Score")
    ax.tick_params(axis="x", rotation=15)
    for bar, val in zip(bars, results_df[metric]):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.003,
                f"{val:.4f}", ha="center", va="bottom", fontsize=8)
plt.suptitle("Perbandingan Model – Semua Metrik Evaluasi", fontsize=13, fontweight="bold")
plt.tight_layout()
run_compare.log({"comparison/metrics_bar_chart": wandb.Image(fig_comp)})
plt.show(); plt.close()

run_compare.finish()
print("[W&B] Run perbandingan selesai.")

"""## Explainable AI (SHAP)"""

# ==========================================================
# 6. EXPLAINABLE AI (SHAP) — dengan W&B Logging
# ==========================================================

import shap

# Ambil ulang model XGBoost (best model dari MODEL_CONFIGS)
xgb_model = MODEL_CONFIGS["XGBoost"]["model"]

run_shap = wandb.init(
    project=WANDB_PROJECT,
    entity=WANDB_ENTITY,
    name="04_shap_explainability",
    tags=["crisp-dm", "shap", "xai", "explainability"],
    config={
        "model": "XGBoost",
        "explainer": "TreeExplainer",
        "n_test_samples": len(X_test),
        "n_features": len(selected_features),
        "explanation_type": "global + local",
    }
)

explainer   = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_test)

# Global Summary Plot
fig_shap_summary = plt.figure()
shap.summary_plot(shap_values, X_test, feature_names=selected_features, show=False)
run_shap.log({"shap/summary_plot": wandb.Image(plt.gcf())})
plt.show(); plt.close()

# Global Bar Plot
fig_shap_bar = plt.figure()
shap.summary_plot(shap_values, X_test, plot_type="bar", show=False)
run_shap.log({"shap/bar_plot_global": wandb.Image(plt.gcf())})
plt.show(); plt.close()

# [WANDB] Log tabel mean |SHAP| per fitur (Global Feature Importance via SHAP)
if isinstance(shap_values, list):
    # format lama: list[kelas]
    shap_abs_mean = np.mean([np.abs(sv) for sv in shap_values], axis=0).mean(axis=0)
else:
    # format baru: 3D array [sample, feature, class]
    shap_abs_mean = np.abs(shap_values).mean(axis=(0, 2))

shap_importance_df = pd.DataFrame({
    "feature": selected_features,
    "mean_abs_shap": shap_abs_mean,
}).sort_values("mean_abs_shap", ascending=False)

run_shap.log({
    "shap/feature_importance_table": wandb.Table(dataframe=shap_importance_df),
})
print("\nTop 10 Fitur (SHAP Global):")
print(shap_importance_df.head(10).to_string(index=False))

# ----- Local Explanation (sampel pertama dari test set) -----
sample_index  = 0
predicted_cls = xgb_model.predict(X_test)[sample_index]

if isinstance(shap_values, list):
    shap_sample    = shap_values[predicted_cls][sample_index]
    expected_value = explainer.expected_value[predicted_cls]
else:
    shap_sample    = shap_values[sample_index, :, predicted_cls]
    expected_value = (
        explainer.expected_value[predicted_cls]
        if hasattr(explainer.expected_value, "__len__")
        else explainer.expected_value
    )

# Force Plot (local)
shap.force_plot(expected_value, shap_sample, X_test.iloc[sample_index], matplotlib=True)
run_shap.log({"shap/local_force_plot_sample0": wandb.Image(plt.gcf())})
plt.show(); plt.close()

# [WANDB] Log tabel SHAP values lokal sampel 0
local_shap_df = pd.DataFrame({
    "feature": selected_features,
    "shap_value": shap_sample,
    "feature_value": X_test.iloc[sample_index].values,
}).sort_values("shap_value", key=abs, ascending=False)

run_shap.log({
    "shap/local_explanation_sample0": wandb.Table(dataframe=local_shap_df),
    "shap/sample0_predicted_class": int(predicted_cls),
    "shap/sample0_true_class": int(y_test[sample_index]),
    "shap/sample0_expected_value": float(expected_value),
})

run_shap.finish()
print("[W&B] Run SHAP selesai.")

"""## Model Save (Joblib)"""

# ==========================================================
# SIMPAN ARTEFAK MODEL
# ==========================================================
import joblib

joblib.dump(xgb_model,         "xgboost_model.pkl")
joblib.dump(scaler,            "scaler.pkl")
joblib.dump(le,                "label_encoder.pkl")
joblib.dump(selected_features, "selected_features.pkl")

print("\n[INFO] Model, scaler, label encoder, dan selected features berhasil disimpan.")

# [WANDB] Upload artefak ke W&B Artifacts (opsional tapi recommended)
run_artifacts = wandb.init(
    project=WANDB_PROJECT,
    entity=WANDB_ENTITY,
    name="05_save_artifacts",
    tags=["artifacts", "deployment"],
)
artifact = wandb.Artifact(
    name="stress-prediction-model",
    type="model",
    description="XGBoost model untuk prediksi tingkat stres mahasiswa (best model)",
    metadata={
        "accuracy": all_results[1]["Accuracy"],   # index 1 = XGBoost
        "f1_macro": all_results[1]["Macro F1"],
        "roc_auc":  all_results[1]["ROC-AUC"],
        "cv_f1_mean": all_results[1]["CV F1 Mean"],
    }
)
for fname in ["xgboost_model.pkl", "scaler.pkl", "label_encoder.pkl", "selected_features.pkl"]:
    if os.path.exists(fname):
        artifact.add_file(fname)

run_artifacts.log_artifact(artifact)
run_artifacts.finish()
print("[W&B] Semua artefak berhasil diupload ke W&B.")

print("\n" + "="*60)
print("SELESAI. Cek dashboard W&B di: https://wandb.ai")
print("="*60)

"""## Deployment"""

# App.py  –  Website Prediksi Tingkat Stres Mahasiswa
# Enhanced UI + SHAP yang informatif untuk user awam

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import builtins
import ast
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ──────────────────────────────────────────────
# PAGE CONFIG (harus pertama)
# ──────────────────────────────────────────────
st.set_page_config(
    page_title="Stress Level Predictor",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ──────────────────────────────────────────────
# CUSTOM CSS
# ──────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Space+Mono:wght@400;700&display=swap');

html, body, [class*="css"] {
    font-family: 'Plus Jakarta Sans', sans-serif;
}

/* Background */
.stApp {
    background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
    min-height: 100vh;
}

/* Main container */
.block-container {
    padding-top: 2rem;
    padding-bottom: 3rem;
}

/* ── Hero Banner ── */
.hero-banner {
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
    border: 1px solid rgba(99, 179, 237, 0.2);
    border-radius: 20px;
    padding: 2.5rem 3rem;
    margin-bottom: 2rem;
    position: relative;
    overflow: hidden;
}
.hero-banner::before {
    content: '';
    position: absolute;
    top: -50%;
    right: -10%;
    width: 400px;
    height: 400px;
    background: radial-gradient(circle, rgba(99,179,237,0.08) 0%, transparent 70%);
    border-radius: 50%;
}
.hero-title {
    font-family: 'Plus Jakarta Sans', sans-serif;
    font-size: 2.4rem;
    font-weight: 800;
    color: #ffffff;
    margin: 0 0 0.5rem 0;
    line-height: 1.2;
}
.hero-subtitle {
    font-size: 1rem;
    color: rgba(255,255,255,0.65);
    margin: 0;
    line-height: 1.6;
    max-width: 600px;
}
.hero-badge {
    display: inline-block;
    background: rgba(99,179,237,0.15);
    border: 1px solid rgba(99,179,237,0.4);
    color: #63b3ed;
    font-size: 0.75rem;
    font-weight: 600;
    padding: 4px 12px;
    border-radius: 20px;
    margin-bottom: 1rem;
    font-family: 'Space Mono', monospace;
    letter-spacing: 0.05em;
}

/* ── Metric Cards ── */
.metric-card {
    background: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 16px;
    padding: 1.5rem;
    text-align: center;
    transition: transform 0.2s, border-color 0.2s;
}
.metric-card:hover {
    transform: translateY(-2px);
    border-color: rgba(99,179,237,0.3);
}
.metric-label {
    font-size: 0.75rem;
    font-weight: 600;
    color: rgba(255,255,255,0.5);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 0.5rem;
}
.metric-value {
    font-family: 'Space Mono', monospace;
    font-size: 2rem;
    font-weight: 700;
    color: #fff;
    line-height: 1;
}
.metric-sub {
    font-size: 0.8rem;
    color: rgba(255,255,255,0.5);
    margin-top: 0.3rem;
}

/* ── Stress Result Card ── */
.result-card-low {
    background: linear-gradient(135deg, #065f46, #064e3b);
    border: 2px solid #10b981;
    border-radius: 20px;
    padding: 2rem 2.5rem;
    text-align: center;
    box-shadow: 0 0 30px rgba(16,185,129,0.2);
}
.result-card-medium {
    background: linear-gradient(135deg, #78350f, #92400e);
    border: 2px solid #f59e0b;
    border-radius: 20px;
    padding: 2rem 2.5rem;
    text-align: center;
    box-shadow: 0 0 30px rgba(245,158,11,0.2);
}
.result-card-high {
    background: linear-gradient(135deg, #7f1d1d, #991b1b);
    border: 2px solid #ef4444;
    border-radius: 20px;
    padding: 2rem 2.5rem;
    text-align: center;
    box-shadow: 0 0 30px rgba(239,68,68,0.2);
}
.result-emoji { font-size: 3.5rem; margin-bottom: 0.5rem; }
.result-label {
    font-size: 1.8rem;
    font-weight: 800;
    color: #fff;
    margin: 0;
}
.result-desc {
    font-size: 0.9rem;
    color: rgba(255,255,255,0.75);
    margin-top: 0.5rem;
}

/* ── Section Headers ── */
.section-header {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    margin-bottom: 1.25rem;
    padding-bottom: 0.75rem;
    border-bottom: 1px solid rgba(255,255,255,0.08);
}
.section-icon {
    font-size: 1.4rem;
}
.section-title {
    font-size: 1.2rem;
    font-weight: 700;
    color: #fff;
    margin: 0;
}
.section-subtitle {
    font-size: 0.8rem;
    color: rgba(255,255,255,0.5);
    margin: 0;
}

/* ── SHAP Explanation Cards ── */
.shap-intro-card {
    background: rgba(99,179,237,0.06);
    border: 1px solid rgba(99,179,237,0.2);
    border-radius: 14px;
    padding: 1.25rem 1.5rem;
    margin-bottom: 1.5rem;
}
.shap-legend-row {
    display: flex;
    gap: 1.5rem;
    margin-top: 0.75rem;
    flex-wrap: wrap;
}
.shap-legend-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.85rem;
    color: rgba(255,255,255,0.8);
}
.legend-dot-red {
    width: 14px; height: 14px;
    background: #f87171;
    border-radius: 3px;
    flex-shrink: 0;
}
.legend-dot-blue {
    width: 14px; height: 14px;
    background: #60a5fa;
    border-radius: 3px;
    flex-shrink: 0;
}

/* ── Feature Insight Cards (Top drivers) ── */
.driver-card {
    background: rgba(255,255,255,0.04);
    border-radius: 10px;
    padding: 0.9rem 1.1rem;
    margin-bottom: 0.6rem;
    display: flex;
    align-items: center;
    gap: 0.85rem;
    border-left: 4px solid transparent;
}
.driver-card-up { border-left-color: #f87171; }
.driver-card-down { border-left-color: #60a5fa; }
.driver-rank {
    font-family: 'Space Mono', monospace;
    font-size: 0.75rem;
    color: rgba(255,255,255,0.35);
    min-width: 20px;
}
.driver-name {
    font-size: 0.9rem;
    font-weight: 600;
    color: #fff;
    flex: 1;
}
.driver-direction {
    font-size: 0.75rem;
    padding: 2px 10px;
    border-radius: 20px;
    font-weight: 600;
}
.driver-direction-up {
    background: rgba(248,113,113,0.15);
    color: #f87171;
}
.driver-direction-down {
    background: rgba(96,165,250,0.15);
    color: #60a5fa;
}
.driver-value {
    font-family: 'Space Mono', monospace;
    font-size: 0.8rem;
    color: rgba(255,255,255,0.5);
    min-width: 55px;
    text-align: right;
}

/* ── Info Box ── */
.info-box {
    background: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.08);
    border-radius: 12px;
    padding: 1rem 1.25rem;
    font-size: 0.85rem;
    color: rgba(255,255,255,0.65);
    line-height: 1.6;
}
.info-box strong { color: rgba(255,255,255,0.9); }

/* ── Probability Bar ── */
.prob-row {
    margin-bottom: 0.85rem;
}
.prob-label-row {
    display: flex;
    justify-content: space-between;
    margin-bottom: 0.3rem;
}
.prob-label { font-size: 0.85rem; color: rgba(255,255,255,0.8); font-weight: 500; }
.prob-pct   { font-family: 'Space Mono', monospace; font-size: 0.85rem; color: #fff; font-weight: 700; }
.prob-bar-bg {
    background: rgba(255,255,255,0.08);
    border-radius: 6px;
    height: 10px;
    overflow: hidden;
}
.prob-bar-fill-low    { height: 100%; background: linear-gradient(90deg,#10b981,#34d399); border-radius: 6px; transition: width 0.8s ease; }
.prob-bar-fill-medium { height: 100%; background: linear-gradient(90deg,#f59e0b,#fbbf24); border-radius: 6px; transition: width 0.8s ease; }
.prob-bar-fill-high   { height: 100%; background: linear-gradient(90deg,#ef4444,#f87171); border-radius: 6px; transition: width 0.8s ease; }

/* ── Sidebar ── */
section[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #1a1a2e 0%, #16213e 100%);
    border-right: 1px solid rgba(255,255,255,0.07);
}
section[data-testid="stSidebar"] .stSlider > div > div > div { background: #63b3ed !important; }

/* ── Charts background transparent ── */
.stPlotlyChart, .stPyplot { background: transparent !important; }

/* ── Streamlit overrides ── */
.stDataFrame { border-radius: 10px; overflow: hidden; }
div[data-testid="stMetric"] { background: rgba(255,255,255,0.04); border-radius: 12px; padding: 1rem; }
.stAlert { border-radius: 12px; }
hr { border-color: rgba(255,255,255,0.08) !important; }
</style>
""", unsafe_allow_html=True)


# ──────────────────────────────────────────────
# LOAD ARTIFACTS
# ──────────────────────────────────────────────
@st.cache_resource
def load_artifacts():
    model             = joblib.load("xgb_model.pkl")
    scaler            = joblib.load("scaler.pkl")
    label_encoder     = joblib.load("label_encoder.pkl")
    selected_features = joblib.load("selected_features.pkl")
    return model, scaler, label_encoder, selected_features

model, scaler, le, selected_features = load_artifacts()

STRESS_CONFIG = {
    0: {
        "label": "Stres Rendah",
        "emoji": "😌",
        "css_class": "result-card-low",
        "color": "#10b981",
        "bar_class": "prob-bar-fill-low",
        "desc": "Kondisi mental Anda tergolong baik. Tetap pertahankan pola hidup sehat!",
    },
    1: {
        "label": "Stres Sedang",
        "emoji": "😐",
        "css_class": "result-card-medium",
        "color": "#f59e0b",
        "bar_class": "prob-bar-fill-medium",
        "desc": "Ada beberapa faktor pemicu stres. Perhatikan istirahat dan manajemen waktu.",
    },
    2: {
        "label": "Stres Tinggi",
        "emoji": "😰",
        "css_class": "result-card-high",
        "color": "#ef4444",
        "bar_class": "prob-bar-fill-high",
        "desc": "Tingkat stres cukup tinggi. Disarankan untuk berbicara dengan konselor atau profesional.",
    },
}

FEATURE_LABELS = {
    "anxiety_level":               "Tingkat Kecemasan",
    "self_esteem":                 "Harga Diri",
    "mental_health_history":       "Riwayat Masalah Mental",
    "depression":                  "Tingkat Depresi",
    "headache":                    "Frekuensi Sakit Kepala",
    "blood_pressure":              "Tekanan Darah",
    "sleep_quality":               "Kualitas Tidur",
    "breathing_problem":           "Masalah Pernapasan",
    "noise_level":                 "Kebisingan Lingkungan",
    "living_conditions":           "Kondisi Tempat Tinggal",
    "safety":                      "Rasa Aman",
    "basic_needs":                 "Kebutuhan Dasar",
    "academic_performance":        "Performa Akademik",
    "study_load":                  "Beban Belajar",
    "teacher_student_relationship":"Hub. Dosen-Mahasiswa",
    "future_career_concerns":      "Kekhawatiran Karir",
    "social_support":              "Dukungan Sosial",
    "peer_pressure":               "Tekanan Teman Sebaya",
    "extracurricular_activities":  "Aktivitas Ekskul",
    "bullying":                    "Perundungan",
    "academic_stress_index":       "Indeks Stres Akademik",
    "environment_quality_index":   "Indeks Kualitas Lingkungan",
    "social_stress_score":         "Skor Stres Sosial",
}


# ──────────────────────────────────────────────
# [FIX] SHAP Monkey-Patch (XGBoost 3.x multiclass)
# ──────────────────────────────────────────────
def patch_shap_for_xgb_multiclass():
    import shap.explainers._tree as _tree_mod
    _OrigLoader = _tree_mod.XGBTreeModelLoader
    _orig_init  = _OrigLoader.__init__
    _orig_float = builtins.float
    if getattr(_OrigLoader, "_patched_for_multiclass", False):
        return

    class _ArrayAwareFloat(float):
        def __new__(cls, x=0):
            if isinstance(x, str):
                try:
                    return _orig_float.__new__(cls, x)
                except (ValueError, TypeError):
                    try:
                        arr = ast.literal_eval(x)
                        return _orig_float.__new__(cls, np.mean(arr))
                    except Exception:
                        return _orig_float.__new__(cls, 0.5)
            return _orig_float.__new__(cls, x)

    def _patched_init(self, xgb_model):
        builtins.float = _ArrayAwareFloat
        try:
            _orig_init(self, xgb_model)
        finally:
            builtins.float = _orig_float

    _OrigLoader.__init__ = _patched_init
    _OrigLoader._patched_for_multiclass = True


@st.cache_resource
def get_shap_explainer(_model):
    import shap
    patch_shap_for_xgb_multiclass()
    return shap.TreeExplainer(_model)


# ──────────────────────────────────────────────
# NORMALISASI & INPUT BUILDER
# ──────────────────────────────────────────────
MINMAX_RANGE = {
    "study_load": (0, 5), "future_career_concerns": (0, 5),
    "academic_performance": (0, 5), "peer_pressure": (0, 5),
    "bullying": (0, 5), "social_support": (0, 3),
}

def minmax_norm_single(value, feat):
    lo, hi = MINMAX_RANGE[feat]
    return (value - lo) / (hi - lo) if hi != lo else 0.0

def build_input_row(raw):
    w_study, w_career, w_acad = 0.6342, 0.7426, 0.7209
    total_w = w_study + w_career + w_acad
    academic_stress_index = (
        (w_study  / total_w) * minmax_norm_single(raw["study_load"], "study_load")
        + (w_career / total_w) * minmax_norm_single(raw["future_career_concerns"], "future_career_concerns")
        + (w_acad   / total_w) * (1 - minmax_norm_single(raw["academic_performance"], "academic_performance"))
    )
    environment_quality_index = (
        raw["noise_level"]
        + (5 - raw["living_conditions"])
        + (5 - raw["safety"])
        + (5 - raw["basic_needs"])
    )
    social_stress_score = (
        minmax_norm_single(raw["peer_pressure"], "peer_pressure")
        + minmax_norm_single(raw["bullying"], "bullying")
        + (1 - minmax_norm_single(raw["social_support"], "social_support"))
    )
    full = {**raw,
            "academic_stress_index": academic_stress_index,
            "environment_quality_index": environment_quality_index,
            "social_stress_score": social_stress_score}
    return pd.DataFrame([full])[selected_features]


# ══════════════════════════════════════════════
# SIDEBAR INPUT
# ══════════════════════════════════════════════
with st.sidebar:
    st.markdown("""
    <div style='padding:1rem 0 1.5rem 0;'>
        <div style='font-family:Space Mono,monospace;font-size:0.7rem;color:rgba(255,255,255,0.4);
                    letter-spacing:0.15em;margin-bottom:0.5rem;'>INPUT MAHASISWA</div>
        <div style='font-size:1.1rem;font-weight:800;color:#fff;'>Isi Data Kamu</div>
        <div style='font-size:0.8rem;color:rgba(255,255,255,0.5);margin-top:0.2rem;'>
            Geser slider sesuai kondisi kamu saat ini
        </div>
    </div>
    """, unsafe_allow_html=True)

    with st.expander("🧠 Faktor Psikologis", expanded=True):
        anxiety_level         = st.slider("Tingkat Kecemasan",        0, 21, 10,
                                          help="0 = tidak cemas sama sekali, 21 = sangat cemas")
        self_esteem           = st.slider("Harga Diri",               0, 30, 15,
                                          help="0 = sangat rendah, 30 = sangat tinggi")
        mental_health_history = st.selectbox("Riwayat Masalah Mental", [0, 1],
                                              format_func=lambda x: "Tidak ada" if x == 0 else "Ada riwayat")
        depression            = st.slider("Tingkat Depresi",           0, 27, 10,
                                          help="0 = tidak ada, 27 = sangat berat")

    with st.expander("🏥 Kesehatan Fisik", expanded=False):
        headache          = st.slider("Frekuensi Sakit Kepala", 0, 5, 2, help="0=tidak pernah, 5=sangat sering")
        blood_pressure    = st.slider("Tekanan Darah",          1, 3, 2, help="1=rendah, 2=normal, 3=tinggi")
        sleep_quality     = st.slider("Kualitas Tidur",         1, 5, 3, help="1=sangat buruk, 5=sangat baik")
        breathing_problem = st.slider("Masalah Pernapasan",     0, 5, 1, help="0=tidak ada, 5=sangat sering")

    with st.expander("🏠 Lingkungan", expanded=False):
        noise_level       = st.slider("Tingkat Kebisingan",        0, 5, 2, help="0=sangat tenang, 5=sangat bising")
        living_conditions = st.slider("Kondisi Tempat Tinggal",    1, 5, 3, help="1=sangat buruk, 5=sangat baik")
        safety            = st.slider("Rasa Aman di Lingkungan",   1, 5, 3, help="1=tidak aman, 5=sangat aman")
        basic_needs       = st.slider("Pemenuhan Kebutuhan Dasar", 1, 5, 3, help="1=tidak terpenuhi, 5=sangat terpenuhi")

    with st.expander("📚 Akademik", expanded=False):
        academic_performance         = st.slider("Performa Akademik",    1, 5, 3, help="1=sangat buruk, 5=sangat baik")
        study_load                   = st.slider("Beban Belajar",        1, 5, 3, help="1=sangat ringan, 5=sangat berat")
        teacher_student_relationship = st.slider("Hub. Dosen-Mahasiswa", 1, 5, 3, help="1=sangat buruk, 5=sangat baik")
        future_career_concerns       = st.slider("Kekhawatiran Karir",   1, 5, 3, help="1=tidak khawatir, 5=sangat khawatir")

    with st.expander("👥 Sosial", expanded=False):
        social_support             = st.slider("Dukungan Sosial",           0, 3, 2, help="0=tidak ada, 3=sangat banyak")
        peer_pressure              = st.slider("Tekanan Teman Sebaya",      1, 5, 3, help="1=tidak ada, 5=sangat tinggi")
        extracurricular_activities = st.slider("Aktivitas Ekstrakurikuler", 0, 5, 2, help="0=tidak ada, 5=sangat aktif")
        bullying                   = st.slider("Tingkat Perundungan",       0, 5, 1, help="0=tidak ada, 5=sangat parah")

    st.markdown("<div style='height:1rem'></div>", unsafe_allow_html=True)
    predict_btn = st.button("🔍 Analisis Sekarang", use_container_width=True, type="primary")


# ══════════════════════════════════════════════
# MAIN CONTENT
# ══════════════════════════════════════════════

# ── Hero Banner ──
st.markdown("""
<div class="hero-banner">
    <div class="hero-badge">🎓 RESEARCH TOOL · XGBoost + SHAP</div>
    <h1 class="hero-title">Prediksi Tingkat Stres<br>Mahasiswa</h1>
    <p class="hero-subtitle">
        Isi data kondisi kamu di sidebar kiri, lalu lihat hasil prediksi berbasis AI
        beserta penjelasan faktor-faktor yang paling mempengaruhi tingkat stresmu.
    </p>
</div>
""", unsafe_allow_html=True)


# ── Proses data input ──
raw_input = {
    "anxiety_level": anxiety_level, "self_esteem": self_esteem,
    "mental_health_history": mental_health_history, "depression": depression,
    "headache": headache, "blood_pressure": blood_pressure,
    "sleep_quality": sleep_quality, "breathing_problem": breathing_problem,
    "noise_level": noise_level, "living_conditions": living_conditions,
    "safety": safety, "basic_needs": basic_needs,
    "academic_performance": academic_performance, "study_load": study_load,
    "teacher_student_relationship": teacher_student_relationship,
    "future_career_concerns": future_career_concerns,
    "social_support": social_support, "peer_pressure": peer_pressure,
    "extracurricular_activities": extracurricular_activities, "bullying": bullying,
}
df_input_raw    = build_input_row(raw_input)
df_input_scaled = pd.DataFrame(scaler.transform(df_input_raw), columns=selected_features)
prediction       = model.predict(df_input_scaled)
prediction_proba = model.predict_proba(df_input_scaled)
pred_class       = int(prediction[0])
cfg              = STRESS_CONFIG[pred_class]


# ══════════════════════════════════════════════
# SECTION 1: HASIL PREDIKSI
# ══════════════════════════════════════════════
st.markdown("""
<div class="section-header">
    <span class="section-icon">🎯</span>
    <div>
        <div class="section-title">Hasil Prediksi</div>
        <div class="section-subtitle">Berdasarkan 23 faktor yang kamu masukkan</div>
    </div>
</div>
""", unsafe_allow_html=True)

col_result, col_prob = st.columns([1, 1.4], gap="large")

with col_result:
    st.markdown(f"""
    <div class="{cfg['css_class']}">
        <div class="result-emoji">{cfg['emoji']}</div>
        <div class="result-label">{cfg['label']}</div>
        <div class="result-desc">{cfg['desc']}</div>
    </div>
    """, unsafe_allow_html=True)

with col_prob:
    st.markdown("""
    <div style='margin-bottom:0.75rem;'>
        <span style='font-size:0.8rem;font-weight:600;color:rgba(255,255,255,0.5);
                     text-transform:uppercase;letter-spacing:0.1em;'>
            Probabilitas per Kelas
        </span>
    </div>
    """, unsafe_allow_html=True)

    proba_labels = ["😌 Stres Rendah", "😐 Stres Sedang", "😰 Stres Tinggi"]
    bar_classes  = ["prob-bar-fill-low", "prob-bar-fill-medium", "prob-bar-fill-high"]

    for i, (lbl, bar_cls) in enumerate(zip(proba_labels, bar_classes)):
        pct  = prediction_proba[0][i]
        w    = int(pct * 100)
        bold = "font-weight:800;color:#fff;" if i == pred_class else ""
        st.markdown(f"""
        <div class="prob-row">
            <div class="prob-label-row">
                <span class="prob-label" style="{bold}">{lbl}</span>
                <span class="prob-pct">{pct:.1%}</span>
            </div>
            <div class="prob-bar-bg">
                <div class="{bar_cls}" style="width:{w}%"></div>
            </div>
        </div>
        """, unsafe_allow_html=True)

    confidence = max(prediction_proba[0])
    st.markdown(f"""
    <div class="info-box" style="margin-top:1rem;">
        <strong>Tingkat Keyakinan Model:</strong> {confidence:.1%}<br>
        <span style="font-size:0.8rem;">
            Model XGBoost menganalisis 23 fitur untuk menghasilkan prediksi ini.
        </span>
    </div>
    """, unsafe_allow_html=True)

st.markdown("<div style='height:0.5rem'></div>", unsafe_allow_html=True)


# ══════════════════════════════════════════════
# SECTION 2: SHAP EXPLANATION
# ══════════════════════════════════════════════
st.markdown("---")
st.markdown("""
<div class="section-header">
    <span class="section-icon">🔬</span>
    <div>
        <div class="section-title">Mengapa Prediksi Ini?</div>
        <div class="section-subtitle">Penjelasan berbasis SHAP — faktor apa yang paling mempengaruhi hasil</div>
    </div>
</div>
""", unsafe_allow_html=True)

# Penjelasan SHAP untuk user awam
st.markdown("""
<div class="shap-intro-card">
    <strong style="color:#63b3ed;font-size:0.95rem;">💡 Apa itu SHAP?</strong>
    <p style="margin:0.5rem 0 0 0;font-size:0.88rem;color:rgba(255,255,255,0.75);line-height:1.7;">
        SHAP adalah teknologi <em>Explainable AI</em> yang menjelaskan <strong style="color:#fff">mengapa</strong>
        model menghasilkan prediksi tertentu — bukan hanya <em>apa</em> hasilnya.
        Setiap faktor diberi skor: semakin besar nilainya, semakin besar pengaruhnya terhadap prediksimu.
    </p>
    <div class="shap-legend-row">
        <div class="shap-legend-item">
            <div class="legend-dot-red"></div>
            <span><strong style="color:#f87171">Mendorong NAIK</strong> — faktor ini meningkatkan risiko stresmu</span>
        </div>
        <div class="shap-legend-item">
            <div class="legend-dot-blue"></div>
            <span><strong style="color:#60a5fa">Mendorong TURUN</strong> — faktor ini mengurangi risiko stresmu</span>
        </div>
    </div>
</div>
""", unsafe_allow_html=True)

if hasattr(model, "get_booster"):
    try:
        import shap

        shap_explainer = get_shap_explainer(model)
        shap_vals      = shap_explainer.shap_values(df_input_scaled)

        if isinstance(shap_vals, list):
            sv = shap_vals[pred_class][0]
            ev = shap_explainer.expected_value[pred_class]
        else:
            sv = shap_vals[0, :, pred_class]
            ev = (shap_explainer.expected_value[pred_class]
                  if hasattr(shap_explainer.expected_value, "__len__")
                  else shap_explainer.expected_value)

        # ── Top Drivers Cards (user-friendly) ──────────────────────
        shap_series  = pd.Series(sv, index=selected_features)
        top_positive = shap_series[shap_series > 0].sort_values(ascending=False).head(5)
        top_negative = shap_series[shap_series < 0].sort_values(ascending=True).head(5)

        col_up, col_down = st.columns(2, gap="large")

        with col_up:
            st.markdown("""
            <div style='margin-bottom:0.75rem;'>
                <span style='color:#f87171;font-weight:700;font-size:0.95rem;'>
                    🔺 Faktor yang Meningkatkan Stres
                </span><br>
                <span style='font-size:0.78rem;color:rgba(255,255,255,0.45);'>
                    Kondisi ini mendorong prediksi ke arah stres lebih tinggi
                </span>
            </div>
            """, unsafe_allow_html=True)
            for rank, (feat, val) in enumerate(top_positive.items(), 1):
                feat_label = FEATURE_LABELS.get(feat, feat)
                st.markdown(f"""
                <div class="driver-card driver-card-up">
                    <span class="driver-rank">#{rank}</span>
                    <span class="driver-name">{feat_label}</span>
                    <span class="driver-direction driver-direction-up">▲ Naik</span>
                    <span class="driver-value">+{val:.3f}</span>
                </div>
                """, unsafe_allow_html=True)

        with col_down:
            st.markdown("""
            <div style='margin-bottom:0.75rem;'>
                <span style='color:#60a5fa;font-weight:700;font-size:0.95rem;'>
                    🔻 Faktor yang Menurunkan Stres
                </span><br>
                <span style='font-size:0.78rem;color:rgba(255,255,255,0.45);'>
                    Kondisi ini mendorong prediksi ke arah stres lebih rendah
                </span>
            </div>
            """, unsafe_allow_html=True)
            if top_negative.empty:
                st.markdown("""
                <div class="info-box">Tidak ada faktor yang secara signifikan menurunkan stres saat ini.</div>
                """, unsafe_allow_html=True)
            else:
                for rank, (feat, val) in enumerate(top_negative.items(), 1):
                    feat_label = FEATURE_LABELS.get(feat, feat)
                    st.markdown(f"""
                    <div class="driver-card driver-card-down">
                        <span class="driver-rank">#{rank}</span>
                        <span class="driver-name">{feat_label}</span>
                        <span class="driver-direction driver-direction-down">▼ Turun</span>
                        <span class="driver-value">{val:.3f}</span>
                    </div>
                    """, unsafe_allow_html=True)

        st.markdown("<div style='height:1.5rem'></div>", unsafe_allow_html=True)

        # ── SHAP Bar Chart (matplotlib) ─────────────────────────────
        st.markdown("""
        <div class="section-header" style="margin-top:0.5rem;">
            <span class="section-icon">📊</span>
            <div>
                <div class="section-title">Kontribusi Semua Faktor</div>
                <div class="section-subtitle">Semakin panjang batang, semakin besar pengaruhnya</div>
            </div>
        </div>
        """, unsafe_allow_html=True)

        sorted_idx   = np.argsort(np.abs(sv))
        sorted_feats = [FEATURE_LABELS.get(selected_features[i], selected_features[i]) for i in sorted_idx]
        sorted_vals  = sv[sorted_idx]
        bar_colors   = ["#f87171" if v > 0 else "#60a5fa" for v in sorted_vals]

        fig, ax = plt.subplots(figsize=(9, 7))
        fig.patch.set_alpha(0)
        ax.set_facecolor("none")

        bars = ax.barh(sorted_feats, sorted_vals, color=bar_colors, height=0.65,
                       edgecolor="none", zorder=3)

        # Value labels
        for bar, val in zip(bars, sorted_vals):
            x_pos = val + (0.002 if val >= 0 else -0.002)
            ha    = "left" if val >= 0 else "right"
            ax.text(x_pos, bar.get_y() + bar.get_height() / 2,
                    f"{val:+.3f}", va="center", ha=ha,
                    fontsize=7.5, color="white", alpha=0.75)

        ax.axvline(0, color=(1, 1, 1, 0.25), linewidth=1, zorder=2)
        ax.set_xlabel("SHAP Value (pengaruh terhadap prediksi)", color="white", fontsize=9, labelpad=8)
        ax.tick_params(axis="y", colors="white", labelsize=8.5)
        ax.tick_params(axis="x", colors=(1, 1, 1, 0.5))
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color((1, 1, 1, 0.1))
        ax.spines["bottom"].set_color((1, 1, 1, 0.1))
        ax.grid(axis="x", color="white", alpha=0.05, linestyle="--", zorder=1)

        red_patch  = mpatches.Patch(color="#f87171", label="Mendorong stres naik")
        blue_patch = mpatches.Patch(color="#60a5fa", label="Mendorong stres turun")
        ax.legend(handles=[red_patch, blue_patch], loc="lower right",
                  framealpha=0.15, labelcolor="white", fontsize=8,
                  facecolor="black", edgecolor=(1, 1, 1, 0.1))

        plt.tight_layout()
        st.pyplot(fig, transparent=True)
        plt.close(fig)

        # ── Waterfall Plot ──────────────────────────────────────────
        st.markdown("""
        <div class="section-header" style="margin-top:1.5rem;">
            <span class="section-icon">🌊</span>
            <div>
                <div class="section-title">Waterfall — Alur Pembentukan Prediksi</div>
                <div class="section-subtitle">
                    Bagaimana nilai awal (E[f(x)]) bergerak step-by-step ke prediksi akhir (f(x))
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("""
        <div class="info-box" style="margin-bottom:1rem;">
            <strong>Cara membaca grafik ini:</strong> Mulai dari nilai dasar model (E[f(x)]),
            setiap baris adalah satu faktor yang "mendorong" prediksi naik (merah) atau turun (biru),
            hingga mencapai prediksi akhirmu f(x) di bagian atas.
        </div>
        """, unsafe_allow_html=True)

        exp = shap.Explanation(
            values=sv,
            base_values=float(ev),
            data=df_input_scaled.iloc[0].values,
            feature_names=[FEATURE_LABELS.get(f, f) for f in selected_features],
        )
        fig2, _ = plt.subplots(figsize=(10, 7))
        fig2.patch.set_alpha(0)
        shap.plots.waterfall(exp, show=False, max_display=15)
        ax2 = plt.gca()
        ax2.set_facecolor("none")
        ax2.tick_params(colors="white")
        for spine in ax2.spines.values():
            spine.set_edgecolor((1, 1, 1, 0.15))
        plt.tight_layout()
        st.pyplot(fig2, transparent=True)
        plt.close(fig2)

    except Exception as e:
        st.error(f"⚠️ SHAP gagal dijalankan: {e}")
        st.code(
            "Pastikan requirements.txt menggunakan:\n"
            "  shap==0.47.0\n"
            "  numpy==1.26.4",
            language="text",
        )


# ══════════════════════════════════════════════
# SECTION 3: DATA INPUT SUMMARY
# ══════════════════════════════════════════════
st.markdown("---")
st.markdown("""
<div class="section-header">
    <span class="section-icon">📋</span>
    <div>
        <div class="section-title">Ringkasan Data Input</div>
        <div class="section-subtitle">Semua nilai yang dimasukkan + fitur turunan yang dihitung otomatis</div>
    </div>
</div>
""", unsafe_allow_html=True)

col_a, col_b = st.columns([2, 1], gap="large")

with col_a:
    raw_df = pd.DataFrame(
        [(FEATURE_LABELS.get(k, k), v) for k, v in raw_input.items()],
        columns=["Faktor", "Nilai Kamu"]
    )
    st.dataframe(raw_df, use_container_width=True, hide_index=True, height=320)

with col_b:
    st.markdown("<div style='font-size:0.85rem;font-weight:600;color:rgba(255,255,255,0.6);margin-bottom:0.75rem;'>Fitur Turunan (Dihitung Otomatis)</div>", unsafe_allow_html=True)

    engineered = {
        "academic_stress_index": df_input_raw["academic_stress_index"].values[0],
        "environment_quality_index": df_input_raw["environment_quality_index"].values[0],
        "social_stress_score": df_input_raw["social_stress_score"].values[0],
    }
    for feat, val in engineered.items():
        label = FEATURE_LABELS.get(feat, feat)
        st.markdown(f"""
        <div class="metric-card" style="margin-bottom:0.75rem;text-align:left;padding:1rem 1.25rem;">
            <div class="metric-label">{label}</div>
            <div class="metric-value" style="font-size:1.4rem;">{val:.4f}</div>
        </div>
        """, unsafe_allow_html=True)


# ── Footer ──
st.markdown("""
<div style='text-align:center;margin-top:3rem;padding-top:1.5rem;
            border-top:1px solid rgba(255,255,255,0.08);'>
    <span style='font-family:Space Mono,monospace;font-size:0.75rem;
                 color:rgba(255,255,255,0.25);letter-spacing:0.08em;'>
        MODEL: XGBoost &nbsp;·&nbsp; EXPLAINABILITY: SHAP TreeExplainer
        &nbsp;·&nbsp; FRAMEWORK: CRISP-DM &nbsp;·&nbsp; UI: Streamlit
    </span>
</div>
""", unsafe_allow_html=True)