# -*- coding: utf-8 -*-
"""CodeTA_StressLevelDataset_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShjaiwILIJS6TLh-nUYxuqJQD7hAaNOP
"""

from google.colab import drive
drive.mount('/content/drive')

# ==========================================================
# BAB III - METODOLOGI PENELITIAN
# Framework: CRISP-DM
# ==========================================================

# ==========================================================
# 1. BUSINESS UNDERSTANDING
# ==========================================================
# Tujuan:
# Membangun model prediksi tingkat stres mahasiswa
# menggunakan Random Forest, XGBoost, dan LightGBM
# serta mengintegrasikan Explainable AI (SHAP)

# ==========================================================
# 2. DATA UNDERSTANDING
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Dataset/StressLevelDataset.csv")

# Visualisasi Distribusi Target
plt.figure(figsize=(6,4))
sns.countplot(x="stress_level", data=df)
plt.title("Distribusi Tingkat Stres Mahasiswa")
plt.xlabel("Stress Level (0=Rendah, 1=Sedang, 2=Tinggi)")
plt.ylabel("Jumlah Mahasiswa")
plt.show()

# Histogram Data Numerik
df.hist(figsize=(18,14), bins=15)
plt.suptitle("Distribusi Seluruh Variabel", fontsize=16)
plt.show()

# Korelasi Variabel
plt.figure(figsize=(14,10))
corr = df.corr()

sns.heatmap(corr, cmap="coolwarm", center=0)
plt.title("Heatmap Korelasi Antar Variabel")
plt.show()

# Korelasi Target
corr_target = df.corr()["stress_level"].sort_values(ascending=False)

plt.figure(figsize=(8,6))
corr_target.drop("stress_level").plot(kind="bar")
plt.title("Korelasi Fitur terhadap Stress Level")
plt.ylabel("Nilai Korelasi")
plt.show()

# Box Plot Fitur Penting dan Target
important_features = ["anxiety_level",
                      "depression",
                      "future_career_concerns",
                      "academic_performance",
                      "social_support"]

plt.figure(figsize=(15,8))

for i, col in enumerate(important_features):
    plt.subplot(2,3,i+1)
    sns.boxplot(x="stress_level", y=col, data=df)

plt.tight_layout()
plt.show()

# Distribusi Fitur Psikologis
psychological = ["anxiety_level", "depression", "self_esteem"]

df[psychological].plot(kind="box", figsize=(8,5))
plt.title("Distribusi Faktor Psikologis")
plt.show()

# ==========================================================
# 3. DATA PREPARATION
# ==========================================================

# ---------- 3.1 Handling Missing Values ----------
# Numerik → median
# Kategorikal → modus

for col in df.columns:
    if df[col].dtype == "object":
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)

# ---------- 3.2 Feature Engineering ----------

# Academic Stress Index
df["academic_stress_index"] = (
    df["study_load"] +
    df["future_career_concerns"] +
    df["peer_pressure"]
) / 3

# Daily Life Stress Index
df["daily_life_stress_index"] = (
    df["noise_level"] +
    df["living_conditions"] +
    df["basic_needs"]
) / 3


# ---------- 3.3 Feature Selection ----------

selected_features = [

    # Daily Activities
    "sleep_quality",
    "headache",
    "blood_pressure",
    "breathing_problem",
    "extracurricular_activities",
    "basic_needs",
    "noise_level",
    "living_conditions",

    # Academic Factors
    "study_load",
    "academic_performance",
    "teacher_student_relationship",
    "future_career_concerns",
    "peer_pressure",

    # Engineered Features
    "academic_stress_index",
    "daily_life_stress_index"
]

# Pastikan hanya kolom yang ada yang digunakan
selected_features = [f for f in selected_features if f in df.columns]

X = df[selected_features]
y = df["stress_level"]

# ---------- 3.4 Encoding Target ----------
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

# ---------- 3.5 Scaling ----------
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=selected_features
)

# ---------- 3.6 Train-Test Split ----------
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# ==========================================================
# 4. MODELING
# ==========================================================

from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from lightgbm import LGBMClassifier
from sklearn.model_selection import cross_val_score

rf = RandomForestClassifier(n_estimators=300, max_depth=12, random_state=42)
xgb_model = xgb.XGBClassifier(
    objective='multi:softprob',
    num_class=len(np.unique(y)),
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)
lgbm = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=10,
    random_state=42
)

models = {
    "Random Forest": rf,
    "XGBoost": xgb_model,
    "LightGBM": lgbm
}

# Cross Validation
for name, model in models.items():
    scores = cross_val_score(model, X_train, y_train, cv=5, scoring="f1_macro")
    print(f"{name} CV Macro F1: {scores.mean():.4f}")

# Training
for model in models.values():
    model.fit(X_train, y_train)

# ==========================================================
# 5. EVALUATION
# ==========================================================

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

results = []

for name, model in models.items():
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average="macro")
    roc = roc_auc_score(y_test, y_prob, multi_class="ovr")

    results.append([name, acc, f1, roc])

    print(f"\n{name}")
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt="d")
    plt.title(f"Confusion Matrix - {name}")
    plt.show()

results_df = pd.DataFrame(
    results,
    columns=["Model", "Accuracy", "Macro F1", "ROC-AUC"]
)

print("\nPerbandingan Model")
print(results_df)

# ==========================================================
# 6. EXPLAINABLE AI (SHAP)
# ==========================================================

import shap

explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_test)

# Global plot
shap.summary_plot(
    shap_values,
    X_test,
    feature_names=selected_features
)

# ===== Local Explanation (FIX FINAL) =====
sample_index = 0

# Ambil kelas prediksi
predicted_class = xgb_model.predict(X_test)[sample_index]

# Ambil shap value untuk sample dan kelas tersebut
shap_sample = shap_values[sample_index, :, predicted_class]

# Ambil expected value untuk kelas tersebut
expected_value = explainer.expected_value[predicted_class]

shap.force_plot(
    expected_value,
    shap_sample,
    X_test.iloc[sample_index],
    matplotlib=True
)

import joblib

# Save the trained XGBoost model
joblib.dump(xgb_model, 'xgb_model.pkl')

# Save the scaler
joblib.dump(scaler, 'scaler.pkl')

# Save the LabelEncoder
joblib.dump(le, 'label_encoder.pkl')

# Save the list of selected features
joblib.dump(selected_features, 'selected_features.pkl')

print("Model, scaler, label encoder, and selected features have been saved.")

"""### **2. Membuat Aplikasi Streamlit**

Sekarang, kita akan membuat sebuah file Python (`app.py`) yang berisi kode untuk aplikasi Streamlit. Aplikasi ini akan memuat model yang sudah dilatih, mengambil input dari pengguna, membuat prediksi, dan menampilkan penjelasan SHAP.

Anda dapat menyalin kode di bawah ini dan menyimpannya sebagai `app.py` di komputer lokal Anda.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# import shap
# import matplotlib.pyplot as plt
# 
# # Load the saved model and preprocessing tools
# @st.cache_resource
# def load_model_and_preprocessors():
#     model = joblib.load('xgb_model.pkl')
#     scaler = joblib.load('scaler.pkl')
#     label_encoder = joblib.load('label_encoder.pkl')
#     selected_features = joblib.load('selected_features.pkl')
#     return model, scaler, label_encoder, selected_features
# 
# model, scaler, le, selected_features = load_model_and_preprocessors()
# 
# # Streamlit App Title
# st.title('Prediksi Tingkat Stres Mahasiswa')
# st.write('Aplikasi ini memprediksi tingkat stres mahasiswa berdasarkan beberapa faktor, serta memberikan penjelasan mengapa prediksi tersebut dihasilkan menggunakan SHAP.')
# 
# # Sidebar for user input
# st.sidebar.header('Input Fitur Mahasiswa')
# 
# def user_input_features():
#     sleep_duration = st.sidebar.slider('Durasi Tidur (jam)', 0.0, 10.0, 7.0)
#     daily_screen_time = st.sidebar.slider('Waktu Layar Harian (jam)', 0.0, 15.0, 4.0)
#     study_load = st.sidebar.slider('Beban Belajar (skala 0-10)', 0.0, 10.0, 5.0)
#     exam_anxiety = st.sidebar.slider('Kecemasan Ujian (skala 0-10)', 0.0, 10.0, 5.0)
#     academic_performance = st.sidebar.slider('Performa Akademik (skala 0-10)', 0.0, 10.0, 7.0)
#     future_career_concerns = st.sidebar.slider('Kekhawatiran Karir Masa Depan (skala 0-10)', 0.0, 10.0, 6.0)
#     teacher_student_relationship = st.sidebar.slider('Hubungan Guru-Murid (skala 0-10)', 0.0, 10.0, 8.0)
#     social_support = st.sidebar.slider('Dukungan Sosial (skala 0-10)', 0.0, 10.0, 7.0)
# 
#     # Recalculate academic_stress_index and screen_sleep_ratio based on user input
#     academic_stress_index = (0.4 * study_load + 0.4 * exam_anxiety - 0.2 * academic_performance)
# 
#     # Handle division by zero for sleep_duration
#     sleep_duration_safe = sleep_duration if sleep_duration != 0 else 0.1
#     screen_sleep_ratio = daily_screen_time / sleep_duration_safe
# 
#     data = {
#         'sleep_duration': sleep_duration,
#         'daily_screen_time': daily_screen_time,
#         'study_load': study_load,
#         'exam_anxiety': exam_anxiety,
#         'academic_performance': academic_performance,
#         'future_career_concerns': future_career_concerns,
#         'teacher_student_relationship': teacher_student_relationship,
#         'social_support': social_support,
#         'academic_stress_index': academic_stress_index,
#         'screen_sleep_ratio': screen_sleep_ratio
#     }
#     features = pd.DataFrame(data, index=[0])
#     return features
# 
# df_input = user_input_features()
# 
# st.subheader('Input Pengguna')
# st.write(df_input)
# 
# # Scale the input features
# df_input_scaled = scaler.transform(df_input[selected_features])
# df_input_scaled_df = pd.DataFrame(df_input_scaled, columns=selected_features)
# 
# # Make prediction
# prediction = model.predict(df_input_scaled_df)
# prediction_proba = model.predict_proba(df_input_scaled_df)
# 
# st.subheader('Hasil Prediksi Tingkat Stres')
# stress_level_map = {0: 'Rendah', 1: 'Sedang', 2: 'Tinggi'}
# predicted_stress_level = stress_level_map[prediction[0]]
# 
# st.write(f'Tingkat Stres yang Diprediksi: **{predicted_stress_level}**')
# st.write('Probabilitas:')
# for i, prob in enumerate(prediction_proba[0]):
#     st.write(f'- {stress_level_map[i]}: {prob:.2f}')
# 
# # SHAP Explanation
# st.subheader('Penjelasan Prediksi (SHAP Values)')
# 
# # Only compute SHAP values if the model is a tree-based model compatible with TreeExplainer
# if hasattr(model, 'get_booster'): # For XGBoost
#     explainer = shap.TreeExplainer(model)
#     shap_values = explainer.shap_values(df_input_scaled_df)
# 
#     # Ensure shap_values is a list of arrays for multi-output models
#     if isinstance(shap_values, list):
#         # For multi-class classification, shap_values will be a list where each element is an array for a class
#         # We need to select the shap values for the predicted class
#         predicted_class_idx = prediction[0]
#         shap_values_for_predicted_class = shap_values[predicted_class_idx][0]
#         expected_value_for_predicted_class = explainer.expected_value[predicted_class_idx]
#     else:
#         # For binary classification or if TreeExplainer returns a single array
#         shap_values_for_predicted_class = shap_values[0]
#         expected_value_for_predicted_class = explainer.expected_value
# 
#     fig, ax = plt.subplots(figsize=(10, 6))
#     shap.force_plot(expected_value_for_predicted_class, shap_values_for_predicted_class, df_input_scaled_df.iloc[0], matplotlib=True, show=False)
#     st.pyplot(fig)
# 
#     st.write('Grafik di atas menunjukkan bagaimana setiap fitur berkontribusi pada prediksi tingkat stres. Warna merah menunjukkan fitur yang mendorong prediksi ke tingkat stres lebih tinggi, sedangkan warna biru mendorong ke tingkat stres lebih rendah.')
# else:
#     st.write('SHAP Explanation tidak tersedia untuk model ini dengan TreeExplainer.')
#

"""### **3. Cara Menjalankan Aplikasi Streamlit**

1.  **Simpan File**: Pastikan file `xgb_model.pkl`, `scaler.pkl`, `label_encoder.pkl`, `selected_features.pkl`, dan `app.py` berada dalam direktori yang sama di komputer lokal Anda.
2.  **Instal Streamlit**: Jika Anda belum menginstalnya, buka terminal atau command prompt dan jalankan:
    ```bash
    pip install streamlit
    pip install shap
    ```
3.  **Jalankan Aplikasi**: Dari direktori yang sama di terminal atau command prompt, jalankan:
    ```bash
    streamlit run app.py
    ```

Ini akan membuka aplikasi Streamlit di browser web default Anda.
"""